# Generated by Django 5.0.6 on 2024-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phno', models.IntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
